---
version: "2"

checks:
  argument-count:
    enabled: false

  file-lines:
    enabled: false

  method-complexity:
    enabled: false

  method-count:
    enabled: false

  similar-code:
    enabled: false

plugins:
  bandit:
    enabled: true

  radon:
    enabled: false

  sonar-python:
    enabled: true

exclude_patterns:
  # default exclude patterns:
  - "config/"
  - "db/"
  - "dist/"
  - "features/"
  - "**/node_modules/"
  - "script/"
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - "Tests/"
  - "**/vendor/"
  - "**/*_test.go"
  - "**/*.d.ts"
