---
version: "3.4"
services:
  runner-3.6: &runner-config
    image: "python:3.6"
    working_dir: /workdir
    volumes:
      - $PWD:/workdir
      # We need to manually bring in buildkite-agent
      # (https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/issues/158)
      - ${BUILDKITE_AGENT_BINARY_PATH:-/usr/bin/buildkite-agent}:/usr/bin/buildkite-agent
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - GIT_BRANCH=$BUILDKITE_BRANCH
      - BUILDKITE_AGENT_ACCESS_TOKEN
      - BUILDKITE_BUILD_NUMBER
      - BUILDKITE_BRANCH
      - AWS_LOGS_BUCKET
      # codecov needs extra info from Buildkite environment:
      - CI
      - BUILDKITE
      - BUILDKITE_PULL_REQUEST
      - BUILDKITE_JOB_ID
      - BUILDKITE_BUILD_URL
      - BUILDKITE_PROJECT_SLUG
      - BUILDKITE_COMMIT
      - BUILDKITE_TAG
      - CODECOV_TOKEN

  runner-3.7:
    <<: *runner-config
    image: "python:3.7"
