steps:
  - label: ":python:"
    command: ".buildkite/script.sh"
    plugins:
      docker#v2.1.0:
        image: "python:3.6"
        environment:
          - PYTHONDONTWRITEBYTECODE=1
          - COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN
          - GIT_BRANCH=$BUILDKITE_BRANCH
          - BUILDKITE_BUILD_NUMBER=${BUILDKITE_BUILD_NUMBER?}
          - BUILDKITE_BRANCH=${BUILDKITE_BRANCH?}
          - AWS_LOGS_BUCKET=${AWS_LOGS_BUCKET}

  - label: "style"
    plugins:
      docker#v2.1.0:
        image: "stellargraph/black"
        command: ["--check", "stellargraph", "tests"]
        environment:
          - PYTHONDONTWRITEBYTECODE=1

  - wait: ~
    continue_on_failure: true

  - label: ":console: push logs"
    command: .buildkite/pushlogs.sh "#build-bots"
