---
timeout: &timeout
  # steps can run for half an hour, maximum: if they haven't finished by then, there's probably some
  # deeper problem. A global timeout would be better
  # (https://github.com/buildkite/feedback/issues/170).
  timeout_in_minutes: 30

compose-config: &compose-config
  config:
    - docker-compose.yml
    - .buildkite/docker-compose.yml

plugins: &plugins
  stellargraph/github-merged-pr#develop:
    mode: checkout

steps:
  - label: ":python: test Conda build"
    <<: *timeout
    command: ".buildkite/steps/test-demo-notebooks.sh"
    plugins:
      <<: *plugins
      docker-compose#v3.2.0:
        <<: *compose-config
        run: conda
    agents:
      queue: "t2medium"

