steps:
  - label: ":python: 3.6"
    command: ".buildkite/steps/script.sh"
    plugins:
      docker#v3.2.0:
        image: "python:3.6"
        environment:
          - PYTHONDONTWRITEBYTECODE=1
          - GIT_BRANCH=$BUILDKITE_BRANCH
          - COVERALLS_REPO_TOKEN
          - BUILDKITE_BUILD_NUMBER
          - BUILDKITE_BRANCH
          - AWS_LOGS_BUCKET
          # for coveralls-python, to send more metadata to coveralls.io
          - BUILDKITE
          - BUILDKITE_PULL_REQUEST
          - BUILDKITE_JOB_ID
    agents:
      queue: 't2medium'

  - label: "style"
    plugins:
      docker#v3.2.0:
        image: "stellargraph/black"
        command: ["--check", "stellargraph", "tests"]
        environment:
          - PYTHONDONTWRITEBYTECODE=1

  - label: ":docker: :hadolint: lint Dockerfiles"
    command: "find -name 'Dockerfile*' -print0 | xargs -0 hadolint"
    plugins:
       docker#v3.2.0:
          image: "hadolint/hadolint:latest-debian"

  - label: ":docker: publish numbered images"
    command: ".buildkite/steps/manage-images.sh build-publish-numbered"
    agents:
      queue: "t2medium"
    branches: "develop feature/*"

  - wait: ~
    continue_on_failure: true

  - label: ":docker: (conditionally) publish docker images"
    command: ".buildkite/utils/checkstatus.sh .buildkite/steps/manage-images.sh publish-images"
    branches: "develop feature/*"

  - wait: ~
    continue_on_failure: true

  - label: ":do_not_litter: delete numbered temporary images"
    command: ".buildkite/steps/manage-images.sh delete-numbered"
    branches: "develop feature/*"

  - wait: ~
    continue_on_failure: true

  - label: ":console: push logs"
    command: .buildkite/utils/pushlogs.sh "#build-bots"
