steps:
  - label: ":python:"
    command:
      - pip install -q --no-cache-dir -r requirements.txt -e .
        && py.test -ra --cov=stellargraph tests/ --doctest-modules --doctest-modules --cov-report=term-missing -p no:cacheprovider
        && coveralls
    plugins:
      docker#v2.1.0:
        image: "python:3.6"
        workdir: /app
        environment:
          - PYTHONDONTWRITEBYTECODE=1
          - COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN

  - label: "style"
    command:
      - --check stellargraph tests
    plugins:
      docker#v2.1.0:
        image: "stellargraph/black"
        workdir: /app
        entrypoint: /usr/bin/black
        environment:
          - PYTHONDONTWRITEBYTECODE=1

  - wait: ~
    continue_on_failure: true

  - label: ":console: push logs"
    command: .buildkite/pushlogs.sh "#build-bots"
